spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - email
              - profile

app:
  oauth2:
    redirectUri: http://localhost:8080/api/auth/google/callback